### ISSUE TITLE
Booking two slots for the same IndividualFacilityUse in the same booking does not update the availability of both slots

### ISSUE THREAD

**Issue by nickevansuk** [playfinder/openactive#1]
The tests below, which are repeatable, demonstrate that booking two slots for the same `IndividualFacilityUse` within one booking request does not update the availability of both slots. Only the second slot is updated.

[non-free-opportunities_opportunity-paid_OpenBookingSimpleFlow_Multiple.md](https://github.com/playfinder/openactive/files/13964385/non-free-opportunities_opportunity-paid_OpenBookingSimpleFlow_Multiple.md)

[last-slots-feed-page.json](https://github.com/playfinder/openactive/files/13964409/last-slots-feed-page.json)

Another clue might be found at the B call, where the error is `"There are no spaces remaining in this opportunity"`. (Noting that due to https://github.com/playfinder/openactive/issues/2 the error may be presented against the wrong slot). This suggests that perhaps the availability checking logic may break when booking two slots for the same `IndividualFacilityUse`?

**Comment by nathansalter** [comment]
This had the same root cause as https://github.com/playfinder/openactive/issues/5 so should be resolved as well now
