### ISSUE TITLE
Missing Criteria: TestOpportunityBookableOutsideValidFromBeforeStartDate

### ISSUE THREAD

**Issue by lukehesluke** [playfinder/openactive#16]
This makes it impossible to pass this test:

- [booking-window_opportunity-outside-range-c1-c2_OpenBookingSimpleFlow_IndividualFacilityUseSlot.html.zip](https://github.com/user-attachments/files/17475536/booking-window_opportunity-outside-range-c1-c2_OpenBookingSimpleFlow_IndividualFacilityUseSlot.html.zip)
    - The summary page also presents this information in a useful way: [summary.html.zip](https://github.com/user-attachments/files/17475539/summary.html.zip)

Specifically, this test needs an opportunity which has a `validFromBeforeStartDate` and is currently outside of the booking window implied by that duration. The other booking-window test (which was successful ✅ ) gives an example of what an opportunity that _does_ have a booking window looks like: [booking-window_opportunity-in-range-c1-c2_OpenBookingSimpleFlow_IndividualFacilityUseSlot.html.zip](https://github.com/user-attachments/files/17475568/booking-window_opportunity-in-range-c1-c2_OpenBookingSimpleFlow_IndividualFacilityUseSlot.html.zip). The salient snippet is here:

![Screenshot 2024-10-22 at 12 49 13](https://github.com/user-attachments/assets/1e18e1fe-9871-4b9f-94ef-b2fb5970d614)

So, what Test Suite needs is a some opportunites which have a booking window like this but are outside of it.

**User Experience impact**: It's not possible to test that an end-user will get an appropriate experience if they try to book something outside of the booking window

**Comment by nathansalter** [comment]
We cannot generate invalid slots in our system, so this kind of test is not suitable as in order for us to provide these, our system would have to be not working as intended

**Comment by nathansalter** [comment]
You could wait for a slot to become unavailable and then try book, which we know works (we see this all the time) but we just can't generate it in our system, there's a lot of redundancy here to stop this from happening in the first place
