### ISSUE TITLE
Fix expansion of acceptedOffer and orderedItem, and Seller, for cases where OrderItem fails

### ISSUE THREAD

**Issue by nickevansuk** [playfinder/openactive#2]
Currently when there's an error with an `OrderItem`, the following invalid response is returned.

`acceptedOffer`, `orderedItem`, and `seller` should be fully expanded for cases where there is an OrderItem `error`.

```
  "orderedItem": [
    {
      "@type": "OrderItem",
      "orderedItem": {
        "@type": "Slot",
        "@id": "/api/open-active/a63e6a0f-f10f-4ea7-ad18-848a4e551834/slots/213a06b1-43fd-5035-b45e-7e200faa2e4a",
        "identifier": "213a06b1-43fd-5035-b45e-7e200faa2e4a"
      },
      "acceptedOffer": {
        "@type": "Offer",
        "@id": "/api/open-active/offers/1707582600-616643d5-56f9-439a-9c6d-a73175d37b80",
        "identifier": "1707582600-616643d5-56f9-439a-9c6d-a73175d37b80"
      },
      "error": [
        {
          "@type": "OpportunityIsFullError",
          "description": "There are no spaces remaining in this opportunity"
        }
      ],
      "position": 0
    }
  ],
```

Failing test result below:
[availability-check_opportunity-full_OpenBookingSimpleFlow_IndividualFacilityUseSlot.md](https://github.com/playfinder/openactive/files/13964927/availability-check_opportunity-full_OpenBookingSimpleFlow_IndividualFacilityUseSlot.md)

Additionally, when multiple `OrderItem`s are included in the booking, the first slot will return invalid data as above (but without the `error`), and one of the other slots appears to contain the `error`, as below:
- [cancellation-window_fail-outside-window_OpenBookingSimpleFlow_Multiple.md](https://github.com/playfinder/openactive/files/13966013/cancellation-window_fail-outside-window_OpenBookingSimpleFlow_Multiple.md)
- [payment-reconciliation-detail-validation_payment-reconciliation-detail-validation_OpenBookingSimpleFlow_Multiple.md](https://github.com/playfinder/openactive/files/13965994/payment-reconciliation-detail-validation_payment-reconciliation-detail-validation_OpenBookingSimpleFlow_Multiple.md)

**Comment by nathansalter** [comment]
This is improved now, but doesn't always return the correct information when it's not detectable

**Comment by lukehesluke** [comment]
The primary issue has been resolved here. The secondary problem is now in a separate issue: https://github.com/playfinder/openactive/issues/8, so I think this can be closed

**Comment by nickevansuk** [comment]
Great thanks @lukehesluke
